webmis/config/routes.rb
MIS::Application.routes.draw do

  get '404', :to =>"errors#not_found"
  get '500', :to => "errors#internal_server_error"
  
  get '/', to: redirect('/webmis')

  scope '/webmis' do
      

    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    root :to => 'main#index'
    resources :allocation_exceptions
    resources :errors do
      get :not_found, :on => :collection
      get :internal_server_error, :on => :collection
    end
    resources :api_logs

    resources :warehouse_stock_adjustments do
      get :onhand, :on => :collection
      post :onhand, :on => :collection
    end

    resources :areas do
      get :generate_dakota_id, :on => :collection
      member do
      end
    end
    resources :area_types
    resources :articles
    resources :article_licenses do
      get :license_fee_report, :on => :collection
      post :html2pdf_license_fee_po, :on => :collection
    end
    resources :assembly_headers do
      member do
        get 'create_csv'
        get 'cloneit'
        get 'table_edit'
        post 'add_checked'
        post 'destroy_line'
        get 'add_tag4mre'
        get 'remove_mre_tag'
        get 'add_update_region_tag'
        get 'replace_data'
        get 'update_coverage_view_by_map'
      end
    end
    resources :assembly_lines
    resources :assets do
      member do

      end
    end
    resources :asset_type_number_ranges
    resources :asset_types do
      get 'create_number', :on => :collection
      post 'create_number', :on => :collection
      member do

      end
    end
    resources :business_processes
    resources :carin_productsets
    resources :cities do
      post 'redirect_to_index' , :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :commitment_change_reasons
    resources :companies do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :company_abbrs, :tags do
      get :dakota_supplier_ids_file, :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :content_release_notes do
      get :get_versions_and_regions_for_project, :on => :collection
      get :get_jira_release_note, :on => :collection
    end
    resources :conversion_databases do
      get :marked_for_removal_index, :on => :collection
      post :batch_mark_for_removal, :on => :collection
      post :db_remove_script, :on => :collection
      get :download_db_remove_script, :on => :collection
      get :render_file_tree, :on => :collection
      member do
        get :handle
        post :change_status
        get :download_stdout_log
        post :mark_for_removal
        post :unmark_for_removal
      end
    end
    resources :conversion_jobs do
      get :failures, :on => :collection
      post :tagging_fail_reason, :on => :collection
      member do
        post :cancel
        post :clean_working_dir
        post :edit_new_copy
        get :edit_new_copy
        post :handle_crashed
        post :reschedule
        get :tail_z_log
        get :terminal
        get :cancel
        post :generated_script
      end
    end
    resources :conversions, :tags do
      get :check_cvtool, :on => :collection
      get :get_cvtool_bundles, :on => :collection
      get :get_datareleases, :on => :collection
      get :get_datareleases_for_overview, :on => :collection
      get :get_production_orders, :on => :collection
      get :import_assembly , :on => :collection
      get :import_process_data , :on => :collection
      get :get_data_by_pid , :on => :collection
      post :check_cvtool, :on => :collection
      post :allocate_data, :on => :collection
      get :cloneit, :on => :collection
      get :show_validation_errors, :on => :collection
      post :handle_validation_errors, :on => :collection
      post :close_validation_errors, :on => :collection
      get :patch_requests_report, :on => :collection
      post :change_year_patch_requests_report, :on => :collection
      get :conversions_for_select, :on => :collection
      get :fill_cloned_attributes, :on => :collection
      member do
        get 'handle'
        get 'report'
        get 'mail'
        post :toggle_mark_for_removal
        get 'tpd'
        get 'to_remove'
        get 'favorite'
        get 'remove_tag'
        get 'reset_outcome'
        get 'fill_marking_for_removal_modal_confirm'
        post 'restart_failed_and_crashed_conversion_jobs'
        post 'toggle_outcome_persistence'
        get :new_patch_request
        get :edit_result
        post :update_result
      end
    end
    resources :config_parameters
    resources :conversion_environments do
      member do
        get :toggle_active_yn
      end
    end
    resources :conversiontools do
      post :sync, :on => :collection
      member do
        post :toggle_isactive
      end
    end
    resources :continents do
      get :generate_dakota_id, :on => :collection
    end
    resources :countries do
      post 'redirect_to_index', :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :country_conversion_productsets
    resources :customer_depots
    resources :cvtool_bundles do
      get :get_cvtool_bundles, :on => :collection
      member do
        post :toggle_active_yn
      end
    end
    resources :cvtool_templates do
      member do
        post :upload_script
        get :sendscript
      end
    end
    resources :dashboard_grid_widgets do
      post :save_position, :on => :collection
    end
    resources :dashboard_widgets do
      get :render_widget, :on => :collection
      get :widget_demo_01, :on => :collection
      get :widget_demo_02, :on => :collection
      get :widget_demo_03, :on => :collection
      get :widget_demo_04, :on => :collection
      member do
        
        get :drop_widget_from_grid
      end
    end
    resources :dashboard_grids do
      get :my_dashboards, :on => :collection
      member do
        get :unused_widgets
      end
    end
    resources :data_media
    resources :data_releases do
      member do
        get :render_prev_data_releases
      end
    end
    resources :data_sets do
      post :filling_for_data_type, :on => :collection
      post :release_for_company_abbr, :on => :collection
      post :update_coverage_regions_list_view, :on => :collection
      get :receptions_for_select, :on => :collection
      post :get_split_by_key, :on => :collection
      get :render_regions_for_input, :on => :collection
      member do
        get :handle
        post :change_status
        get :clone
        put :duplicate
        patch :duplicate
        post :add_to_group
        post :remove_from_group
        post :create_group
        get :check_production_order
        post :checked_production_order
        post :create_production_order
        get :edit_process_data_elements
        get :browse_directory
        post :save_process_data_element
        post :remove_process_data_element
        post :save_process_data_element_action_log
        post :save_poi_mapping_layout
        post :sync_with_directory_structure
        get :validate_structure
        get :element_counter
        get :show_process_data_elements
        get :download_file
        get :render_data_set_pre_selection
        post :request_review
        post :review_result
        get :in_use_orders
        get :show_jobs_modal
      end
    end
    resources :data_set_groups do
      post :release_for_company_abbr, :on => :collection
      post :filling_for_data_type, :on => :collection
      member do
        get :handle
        post :remove
        post :restore
        get :clone
        get :check_production_order
      end
    end
    resources :data_types do
      post 'add_filling_to_list', :on => :collection
      post 'remove_filling_from_list', :on => :collection
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :data_type_versions
    resources :default_content_release_notes do
      get 'ranking', :on => :collection
      member do
        get :rank_it
      end
    end
    resources :distribution_list_members
    resources :distribution_lists do
      member do
        get 'delete_y'
        get 'select_new_hard_copies'
      end
    end
    resources :documents do
      post :create_from_external_controller, :on => :collection
      member do
        get 'download'
        get 'select'
        get :delete
      end
    end
    resources :external_contacts do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :file_transfer_accounts do
      get 'new'
      member do
        get 'new'

      end
    end
    resources :fillings do
      member do
        get 'handle'
        post 'remove'
        post 'restore'
        post 'deactivate'
        post 'activate'
      end
    end
    resources :high_level_boms do
      get 'get_product_locations', :on => :collection
      member do

      end
    end
    resources :inbound_orderlines
    resources :invoices do
      member do
        post :invoice
        post :paid
        get :print
        get :credit_invoice
      end
    end
    resources :job_fail_reasons
    resources :jobs do
      get :tagged_failed_jobs_report, :on => :collection
    end
    resources :licenses
    resources :locations
    resources :main do
      get  'routes', :on => :collection
      get  'archive', :on => :collection
      get  'administration', :on => :collection
      get  'shipping', :on => :collection
      get  'portfolio', :on => :collection
      get  'denied', :on => :collection
      post 'searchit', :on => :collection
      get 'searchit', :on => :collection
      get 'change_project', :on => :collection
      get :get_json_file_tree , :on => :collection
      member do

webmis/app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_filter :authorize, :except => [:get_region_id, :dakota_region_ids, :dakota_names, :test_areas]
  authorize_resource :except => [:get_region_id, :dakota_region_ids, :dakota_names, :test_areas]

  layout "webmis"
  helper_method :sort_column, :sort_direction, :search

  def index
    conditions = "(regions.isactive = 1)"
    @inactive = false
    @test_areas_only = false

    if params[:reset]
      params.delete :q
      params.delete :ruby_type
      params.delete :reset

      if params[:inactive] == "1"
        params.delete :inactive
        @inactive = false
      end

      if params[:test_areas_only] == "1"
        params.delete :test_areas_only
        @test_areas_only = false
      end

      params[:sort] = 'regions.name'
      params[:direction] = 'asc'
    end

    conditions_string_ary = []
    conditions_param_values = []

    if ( params[:inactive] && params[:inactive] == "1" )
      @inactive = true
      conditions = "(1=1)"
    end

    ruby_type = params[:ruby_type]
    unless ruby_type.blank?
      conditions_string_ary << " and (ruby_type = ?)"
      conditions_param_values << ruby_type.gsub(' ','_').camelize
    end

    unless params[:q].blank?
      conditions_string_ary << " and (regions.name LIKE ? OR
                                      continent_code LIKE ? OR
                                      country_iso_code LIKE ? OR
                                      country_iso3_code LIKE ? OR
                                      city_iso_code LIKE ? OR
                                      state_code LIKE ? OR
                                      area_code LIKE ? OR
                                      test_area_configurations.name LIKE ? OR
                                      regions.dakota_id = #{params[:q].strip.to_i})"
      8.times do
        conditions_param_values << "\%#{params[:q].strip}\%"
      end
    end

    if ( params[:test_areas_only] && params[:test_areas_only] == "1" )
      @test_areas_only = true
      conditions_string_ary << ( "AND ( test_area_configurations.region_id = regions.id )" )
    end

    conditions = conditions + conditions_string_ary.join(" ")
    @regions = Region.eager_load(:test_area_configurations).where([conditions] + conditions_param_values).order(sort_column + ' ' + sort_direction).paginate(:per_page => 75, :page => params[:page])
    generate_id_sequence_cookie(@regions,params[:page])

    if request.xhr?
      flash.keep[:notice]
      render(:partial => "region", :collection => @regions)
    end
  end

  def dakota_region_ids_file
    send_data Region.dakota_region_ids_file, :filename => 'REGION_IDS.TXT'
  end

  def dakota_names_file
    send_data Region.dakota_names_file, :filename => 'NAMES.TXT'
  end

  def test_area_configurations
    @region = Region.find(params[:id])
    @test_area_configurations = @region.test_area_configurations.order("product_line_id,min_x,min_y")
  end

  def render_tac_frm
    @region = Region.find(params[:id])
    if params[:test_area_configuration_id].blank?
      @test_area_configuration = TestAreaConfiguration.new(:region_id => @region.id,:nr_of_test_areas_x=>1,:nr_of_test_areas_y=>1)
    else
      @test_area_configuration = @region.test_area_configurations.where(:id => params[:test_area_configuration_id]).last
    end
  end

  def create_test_area_configuration
    @region = Region.find(params[:id])
    params.delete("action")
    params.delete("controller")
    params.delete("id")
    begin
      @test_area_configuration = TestAreaConfiguration.new(params)
      @test_area_configuration.region_id = @region.id
      @test_area_configuration.save!
    rescue => e
      @errors = e.message
    end
  end

  def update_test_area_configuration
    @region = Region.find(params[:id])
    params.delete("action")
    params.delete("controller")
    params.delete("id")
    begin
      @test_area_configuration = TestAreaConfiguration.find(params[:test_area_configuration_id])
      params.delete("test_area_configuration_id")
      @test_area_configuration.assign_attributes(params)
      @test_area_configuration.region_id = @region.id
      @test_area_configuration.save!
    rescue => e
      @errors = e.message
    end
  end

  def delete_test_area_configuration
    @region = Region.find(params[:id])
    @test_area_configuration = TestAreaConfiguration.find(params[:test_area_configuration_id])
    @test_area_configuration.destroy
    flash[:notice] = "#{@test_area_configuration.name} removed."
    respond_to do |format|
      format.html { redirect_to test_area_configurations_region_path(@region) }
      format.json { head :no_content }
    end
  end

  def download_test_areas_exact_script
    @test_area_configuration = TestAreaConfiguration.find(params[:test_area_configuration_id])
    send_data @test_area_configuration.generate_exact_script,
      :filename => @test_area_configuration.file_name("scr")
  end

  def render_tac_generation
    @region = Region.find(params[:id])
    @test_area_configuration = TestAreaConfiguration.find(params[:test_area_configuration_id])
  end

#merged from backoffice
  def get_region_id
    # Designed based on CVENV method cv_privatelib
    region_id = '-1'
    if !params[:areacode].blank?
      region = Region.find_by_region_code(params[:areacode].strip)
      if region && !region.dakota_id.blank?
        region_id = region.dakota_id.to_s
      end
    end
    render :text => region_id
  end

  def dakota_region_ids
    render :text => Region.dakota_region_ids
  end

  def dakota_names
    render :text => Region.dakota_names
  end

  def test_areas
    txt = ""
    region = Region.find_by_region_code(params[:region_code].strip)
    if !params[:target_platform_name].blank? && region
      tp = TargetPlatform.find_by_name(params[:target_platform_name].strip)
      txt = region.test_area_configurations_string(tp.id) if tp
    else
      txt = region.test_area_configurations_string if region
    end
    txt = "NO TEST AREAS FOUND FOR: #{params[:region_code]} #{params[:target_platform_name]}" if txt == ""
    render :text => txt + "\n"
  end

  private
    def sort_column
      params[:sort] || "regions.name"
    end

    def sort_direction
      params[:direction] || "asc"
    end

    def search
      params[:q] || ""
    end
  
end

webmis/app/views/regions/_region.html.erb
<div class="row">
  <div class="span1">
    <div class="btn-group">
      <a class="btn btn-mini dropdown-toggle btn-info" data-toggle="dropdown" href="#">
        Action
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to(region) do %>
          <i class="icon-info-sign"></i>&nbsp;show
          <% end %>
        </li>
        <% if env_production? %>
        <li>
          <%= link_to({:controller => region.ruby_type.tableize, :action => 'edit', :id => region.id}) do %>
          <i class="icon-edit"></i>&nbsp;edit
          <%  end %>
        </li>
        <% end %>
        <% if region.real_region? %>
        <li>
          <%= link_to(test_area_configurations_region_path(region)) do %>
            <i class="icon-wrench"></i>&nbsp;Test area configuration
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>  
  <div class="span3"><%= region.name %>&nbsp;</div>
  <div class="span1"><%= region.region_code %>&nbsp;</div>
  <div class="span3"><%= region.parent.name if region.parent  %>&nbsp;</div>
  <div class="span1"><%= region.ruby_type.tableize.singularize.humanize %></div>
  <div class="span1"><%= bootstrap_boolean(region.isactive) %></div>
</div>

webmis/app/views/regions/_tac.html.erb
<div class="row">
  <div class="span2">
    <%= tac.name %>
  </div>
  <div class="span1 text-center">
    <%= tac.amount_test_areas %>
  </div>
  <div class="span1 text-center">
    <%= tac.nr_of_test_areas_x %>
  </div>
  <div class="span1 text-center">
    <%= tac.nr_of_test_areas_y %>
  </div>
  <div class="span1">
    <%= tac.min_x %>
  </div>
  <div class="span1">
    <%= tac.min_y %>
  </div>
  <div class="span1">
    <%= tac.max_x %>
  </div>
  <div class="span1">
    <%= tac.max_y %>
  </div>
  <div class="span2">
    <%= tac.product_line.name if tac.product_line %>
  </div>
  <div class="span">
    <%= link_to({:action => :download_test_areas_exact_script,:test_area_configuration_id => tac.id },
      {:class => "btn btn-mini", :title => "download exact script"}) do %>
     <i class="icon-map-marker"></i>
    <% end %>
    <button id="btnGenerate-<%= tac.id %>" type="button" class="btn btn-mini" title="generate test areas"><i class="icon-screenshot"></i></button>
    <button id="btnEdit-<%= tac.id %>" type="button" class="btn btn-mini" title="edit configuration"><i class="icon-edit"></i></button>
    <%= link_to({:action => :delete_test_area_configuration,:test_area_configuration_id => tac.id },
      {:class => "btn btn-mini", :title => "delete configuration",:confirm => "Are you sure to delete this configuration permanently?"}) do %>
     <i class="icon-trash"></i>
    <% end %>
  </div>
</div>

webmis/app/views/regions/_tac_generation_modal.html.erb
<div class="row">
  <div class="span5">
    <strong>Test areas:</strong>
  </div>
</div>
<div class="row">
  <div class="span5">
    <%= raw hash_to_html(@test_area_configuration.generate_areas,nil) %>
  </div>
</div>
<div class="row">
  <div class="span5">
    <strong>Exact script:</strong>
  </div>
</div>
<div class="row">
  <div class="span5">
    <pre class="real-pre"><small><%= raw  @test_area_configuration.generate_exact_script.html_safe %></small></pre>
  </div>
</div>

webmis/app/views/regions/create_test_area_configuration.js.erb
<% if @errors.blank? %>
  window.location.replace('<%= url_for(test_area_configurations_region_path(@region)) %>');
<% else %>
  $("#myModalAlert").html('<%= @errors %>').removeClass('hidden');
<% end %>

webmis/app/views/regions/index.html.erb
<div class="navbar secondnav">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand"><strong>All Regions</strong></div>
      <div class="span">
        <%= form_tag regions_path, :method => 'get' do %>
          <div class="span">
              <%= check_box_tag 'inactive', "1", @inactive,{:data => {"text-label" => "inactive","off-label" => "","on-label" => "Include",:size => "normal",:on => "success",:off => "default","off-label" => "excluded"}} %>
              &nbsp;
              <%= check_box_tag 'test_areas_only', "1", @test_areas_only,{:data => {"text-label" => "test areas","off-label" => "","on-label" => "Only",:size => "normal",:on => "success",:off => "default","off-label" => "unfiltered"}} %>
          </div>&nbsp;
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <div class="input-prepend input-append">
            <% if env_production? %>
            <div class="btn-group" style="vertical-align: top">
              <a class="btn btn-dropdown-toggle btn-info" data-toggle="dropdown" href="#">
                New
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to(new_area_path) do %>
                  <i class="icon-globe"></i>&nbsp;Area
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_city_path) do %>
                  <i class="icon-globe"></i>&nbsp;City
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_continent_path) do %>
                  <i class="icon-globe"></i>&nbsp;Continent
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_country_path) do %>
                  <i class="icon-globe"></i>&nbsp;Country
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_region_alias_path) do %>
                  <i class="icon-globe"></i>&nbsp;Region Alias
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_state_path) do %>
                  <i class="icon-globe"></i>&nbsp;State
                  <% end %>
                </li>
                <li>
                  <%= link_to(new_update_region_path) do %>
                  <i class="icon-globe"></i>&nbsp;Update region
                  <% end %>
                </li>
              </ul>
            </div>
            <% end %>
            <%= text_field_tag :q, params[:q], :placeholder=>" search",:class=>"span3",:size=>"16" %>
            <%= select_tag :ruby_type,options_for_select(["Area", "City", "Continent", "Country", "Region alias", "State", "Update region"],params[:ruby_type]),:include_blank=>true,:class => 'span1_5' %>
            <%= button_tag "Search", :name => nil, :type => :submit, :class => "btn" %>
            <%= button_tag "Reset", :name => 'reset',:class=>"btn",:type=>:submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="endless">
  <div class="row">
    <div class="offset1 span3"><strong><%=  sortable "regions.name", "Name" %></strong></div>
    <div class="span1"><strong>Region&nbsp;code</strong></div>
    <div class="span3"><strong><%= sortable "parent_id","Parent" %></strong></div>
    <div class="span1"><strong><%= sortable "ruby_type","Type" %></strong></div>
    <div class="span3"><strong><%= sortable "isactive", 'Active' %></strong></div> 
  </div>

  <%= render(:partial => "region", :collection => @regions) %>
</div>
<%= will_paginate(@regions) %>
<%= pageless(@regions.total_pages, url_for(:controller => :regions, :action => :index), "#endless") %>
<footer class="subnav subnav-fixed" style="bottom:0;top:auto;margin-bottom: 0px;"></footer>

<script type="text/javascript">
  $("#inactive").bootstrapSwitch();
  $("#test_areas_only").bootstrapSwitch();
  $("#ruby_type").chosen({placeholder:"Type"});
</script>

webmis/app/views/regions/index.js.erb
$('#endless').html('<%= escape_javascript(render("region")) %>');

webmis/app/views/regions/render_tac_frm.js.erb
$("#modalBody").html('<%= escape_javascript(render :partial => "tac_modal_frm", :object => [@region,@test_area_configuration]) %>');

webmis/app/views/regions/render_tac_generation.js.erb
$("#modalBody").html('<%= escape_javascript(render :partial => "tac_generation_modal", :object => [@region,@test_area_configuration]) %>');
$("#myModalbtn").addClass("hidden");

webmis/app/views/regions/test_area_configurations.html.erb
<% if @region.real_region? %>

<div class="row">
  <div class="span12 bounded bounded-headered">
    <div class="row bounded-header">
      <div class="span10"><h4>Test area Configuration(s) for region "<%= @region.name %>"</h4></div>
      <div class="span2"><button class="btn pull-right" id="btnNew">New configuration</button></div>
    </div>
    <div class="row">
      <div class="span2">
        <strong>Name</strong>
      </div>
      <div class="span1">
        <strong>Amount</strong>
      </div>
      <div class="span1">
        <strong>Amount X</strong>
      </div>
      <div class="span1">
        <strong>Amount Y</strong>
      </div>
      <div class="span1">
        <strong>min X</strong>
      </div>
      <div class="span1">
        <strong>min Y</strong>
      </div>
      <div class="span1">
        <strong>max X</strong>
      </div>
      <div class="span1">
        <strong>max Y</strong>
      </div>
      <div class="span2">
        <strong>Product line</strong>
      </div>
    </div>
    <div id="tacList">
      <%= render :partial => "tac", :collection => @test_area_configurations %>
    </div>
  </div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="myModalLabel">Test area configuration</h4>
  </div>
  <div class="modal-body" id="modalBody">
    <!--- dynamic content via ajax --->
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary disabled" type="button" id="myModalbtn">Save</button>
  </div>
</div>


<script type="text/javascript">
  $("#btnNew").click(function(){
    $.get('<%= url_for(render_tac_frm_region_path(@region)) %>');
    $("#myModal").modal("show");
  });
  $("[id^=btnGenerate]").click(function(){
    var dbIdA = $(this).attr('id').match(/btnGenerate-([0-9]+)/);
    var dbId = dbIdA[1];
    $.get('<%= url_for(render_tac_generation_region_path(@region)) %>?test_area_configuration_id='+dbId);
    $("#myModal").modal("show");
  });
  $("[id^=btnEdit-]").click(function(){
    var dbIdA = $(this).attr('id').match(/btnEdit-([0-9]+)/);
    var dbId = dbIdA[1];
    $.get('<%= url_for(render_tac_frm_region_path(@region)) %>?test_area_configuration_id='+dbId);
    $("#myModal").modal("show");
  });
  $("[id^=btnDelete-]").click(function(){
    if (confirm('Are you sure to delete this configuration permanently?')) {
            alert("btn delete");
        }
  });

  $('#myModal').on('hidden', function () {
    $("#modalBody").html('');
    $("#myModalbtn").removeClass("hidden");
  })
</script>

<% else %>
  <div><h4>Test area configuration for "<%= @region.name %>" not available</h4></div>
  <div class="row">
    <div class="alert alert-info span5">
      This region is a <%= @region.ruby_type.underscore.humanize %>. For this type no test area configuration is possible.
    </div>
  </div>
<% end %>

<div class="row">
  <div class="span12">
    <%= link_to(:back,:class=>'btn',:title=>'back') do %>
      <i class="icon icon-arrow-left"></i>
    <% end %>
    <%= link_to(regions_path,:class=>'btn',:title=>'Regions overview') do %>
      <i class="icon icon-arrow-up"></i>
    <% end %>
    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
  </div>
</div>

webmis/app/views/regions/update_test_area_configuration.js.erb
<% if @errors.blank? %>
  window.location.replace('<%= url_for(test_area_configurations_region_path(@region)) %>');
<% else %>
  $("#myModalAlert").html('<%= @errors %>').removeClass('hidden');
<% end %>