webmis/config/routes.rb
MIS::Application.routes.draw do

  get '404', :to =>"errors#not_found"
  get '500', :to => "errors#internal_server_error"
  
  get '/', to: redirect('/webmis')

  scope '/webmis' do
      

    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    root :to => 'main#index'
    resources :allocation_exceptions
    resources :errors do
      get :not_found, :on => :collection
      get :internal_server_error, :on => :collection
    end
    resources :api_logs

    resources :warehouse_stock_adjustments do
      get :onhand, :on => :collection
      post :onhand, :on => :collection
    end

    resources :areas do
      get :generate_dakota_id, :on => :collection
      member do
      end
    end
    resources :area_types
    resources :articles
    resources :article_licenses do
      get :license_fee_report, :on => :collection
      post :html2pdf_license_fee_po, :on => :collection
    end
    resources :assembly_headers do
      member do
        get 'create_csv'
        get 'cloneit'
        get 'table_edit'
        post 'add_checked'
        post 'destroy_line'
        get 'add_tag4mre'
        get 'remove_mre_tag'
        get 'add_update_region_tag'
        get 'replace_data'
        get 'update_coverage_view_by_map'
      end
    end
    resources :assembly_lines
    resources :assets do
      member do

      end
    end
    resources :asset_type_number_ranges
    resources :asset_types do
      get 'create_number', :on => :collection
      post 'create_number', :on => :collection
      member do

      end
    end
    resources :business_processes
    resources :carin_productsets
    resources :cities do
      post 'redirect_to_index' , :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :commitment_change_reasons
    resources :companies do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :company_abbrs, :tags do
      get :dakota_supplier_ids_file, :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :content_release_notes do
      get :get_versions_and_regions_for_project, :on => :collection
      get :get_jira_release_note, :on => :collection
    end
    resources :conversion_databases do
      get :marked_for_removal_index, :on => :collection
      post :batch_mark_for_removal, :on => :collection
      post :db_remove_script, :on => :collection
      get :download_db_remove_script, :on => :collection
      get :render_file_tree, :on => :collection
      member do
        get :handle
        post :change_status
        get :download_stdout_log
        post :mark_for_removal
        post :unmark_for_removal
      end
    end
    resources :conversion_jobs do
      get :failures, :on => :collection
      post :tagging_fail_reason, :on => :collection
      member do
        post :cancel
        post :clean_working_dir
        post :edit_new_copy
        get :edit_new_copy
        post :handle_crashed
        post :reschedule
        get :tail_z_log
        get :terminal
        get :cancel
        post :generated_script
      end
    end
    resources :conversions, :tags do
      get :check_cvtool, :on => :collection
      get :get_cvtool_bundles, :on => :collection
      get :get_datareleases, :on => :collection
      get :get_datareleases_for_overview, :on => :collection
      get :get_production_orders, :on => :collection
      get :import_assembly , :on => :collection
      get :import_process_data , :on => :collection
      get :get_data_by_pid , :on => :collection
      post :check_cvtool, :on => :collection
      post :allocate_data, :on => :collection
      get :cloneit, :on => :collection
      get :show_validation_errors, :on => :collection
      post :handle_validation_errors, :on => :collection
      post :close_validation_errors, :on => :collection
      get :patch_requests_report, :on => :collection
      post :change_year_patch_requests_report, :on => :collection
      get :conversions_for_select, :on => :collection
      get :fill_cloned_attributes, :on => :collection
      member do
        get 'handle'
        get 'report'
        get 'mail'
        post :toggle_mark_for_removal
        get 'tpd'
        get 'to_remove'
        get 'favorite'
        get 'remove_tag'
        get 'reset_outcome'
        get 'fill_marking_for_removal_modal_confirm'
        post 'restart_failed_and_crashed_conversion_jobs'
        post 'toggle_outcome_persistence'
        get :new_patch_request
        get :edit_result
        post :update_result
      end
    end
    resources :config_parameters
    resources :conversion_environments do
      member do
        get :toggle_active_yn
      end
    end
    resources :conversiontools do
      post :sync, :on => :collection
      member do
        post :toggle_isactive
      end
    end
    resources :continents do
      get :generate_dakota_id, :on => :collection
    end
    resources :countries do
      post 'redirect_to_index', :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :country_conversion_productsets
    resources :customer_depots
    resources :cvtool_bundles do
      get :get_cvtool_bundles, :on => :collection
      member do
        post :toggle_active_yn
      end
    end
    resources :cvtool_templates do
      member do
        post :upload_script
        get :sendscript
      end
    end
    resources :dashboard_grid_widgets do
      post :save_position, :on => :collection
    end
    resources :dashboard_widgets do
      get :render_widget, :on => :collection
      get :widget_demo_01, :on => :collection
      get :widget_demo_02, :on => :collection
      get :widget_demo_03, :on => :collection
      get :widget_demo_04, :on => :collection
      member do
        
        get :drop_widget_from_grid
      end
    end
    resources :dashboard_grids do
      get :my_dashboards, :on => :collection
      member do
        get :unused_widgets
      end
    end
    resources :data_media
    resources :data_releases do
      member do
        get :render_prev_data_releases
      end
    end
    resources :data_sets do
      post :filling_for_data_type, :on => :collection
      post :release_for_company_abbr, :on => :collection
      post :update_coverage_regions_list_view, :on => :collection
      get :receptions_for_select, :on => :collection
      post :get_split_by_key, :on => :collection
      get :render_regions_for_input, :on => :collection
      member do
        get :handle
        post :change_status
        get :clone
        put :duplicate
        patch :duplicate
        post :add_to_group
        post :remove_from_group
        post :create_group
        get :check_production_order
        post :checked_production_order
        post :create_production_order
        get :edit_process_data_elements
        get :browse_directory
        post :save_process_data_element
        post :remove_process_data_element
        post :save_process_data_element_action_log
        post :save_poi_mapping_layout
        post :sync_with_directory_structure
        get :validate_structure
        get :element_counter
        get :show_process_data_elements
        get :download_file
        get :render_data_set_pre_selection
        post :request_review
        post :review_result
        get :in_use_orders
        get :show_jobs_modal
      end
    end
    resources :data_set_groups do
      post :release_for_company_abbr, :on => :collection
      post :filling_for_data_type, :on => :collection
      member do
        get :handle
        post :remove
        post :restore
        get :clone
        get :check_production_order
      end
    end
    resources :data_types do
      post 'add_filling_to_list', :on => :collection
      post 'remove_filling_from_list', :on => :collection
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :data_type_versions
    resources :default_content_release_notes do
      get 'ranking', :on => :collection
      member do
        get :rank_it
      end
    end
    resources :distribution_list_members
    resources :distribution_lists do
      member do
        get 'delete_y'
        get 'select_new_hard_copies'
      end
    end
    resources :documents do
      post :create_from_external_controller, :on => :collection
      member do
        get 'download'
        get 'select'
        get :delete
      end
    end
    resources :external_contacts do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :file_transfer_accounts do
      get 'new'
      member do
        get 'new'

      end
    end
    resources :fillings do
      member do
        get 'handle'
        post 'remove'
        post 'restore'
        post 'deactivate'
        post 'activate'
      end
    end
    resources :high_level_boms do
      get 'get_product_locations', :on => :collection
      member do

      end
    end
    resources :inbound_orderlines
    resources :invoices do
      member do
        post :invoice
        post :paid
        get :print
        get :credit_invoice
      end
    end
    resources :job_fail_reasons
    resources :jobs do
      get :tagged_failed_jobs_report, :on => :collection
    end
    resources :licenses
    resources :locations
    resources :main do
      get  'routes', :on => :collection
      get  'archive', :on => :collection
      get  'administration', :on => :collection
      get  'shipping', :on => :collection
      get  'portfolio', :on => :collection
      get  'denied', :on => :collection
      post 'searchit', :on => :collection
      get 'searchit', :on => :collection
      get 'change_project', :on => :collection
      get :get_json_file_tree , :on => :collection
      member do

webmis/app/views/validation_jobs/_failed_validation_job.html.erb
<div class="row" id="row-<%= failed_validation_job.id %>">
  <div class="span1">
    <div class="btn-group">
      <a class="btn btn-mini dropdown-toggle btn-info" data-toggle="dropdown" href="#">
        Action
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to(failed_validation_job) do %>
          <i class="icon-info-sign"></i>&nbsp;show
          <% end %>
        </li>
        <li>
          <%= link_to(edit_validation_job_path(failed_validation_job)) do %>
          <i class="icon-edit"></i>&nbsp;edit
          <%  end %>
        </li>
        <% if failed_validation_job.status < Job::STATUS_CANCELLED %>
          <li>
            <%= link_to cancel_validation_job_path(failed_validation_job, {:lock_version => failed_validation_job.lock_version.to_s}), method: :post  do %>
            <i class="icon-off"></i>&nbsp;cancel
            <%  end %>
          </li>
         <% end  %>
      </ul>
    </div>
    <input type="checkbox" name="checked" value="<%= failed_validation_job.id %>" class="pull-right" id="chk-<%= failed_validation_job.id %>"/>
  </div>

  <div class="span1">
    <%= failed_validation_job.id %>
  </div>

  <div class="span2">
    <%= failed_validation_job.status_str %>
  </div>

  <div class="span4">
    
      <%= "#{failed_validation_job.conversion_database.id} | #{failed_validation_job.conversion_database.shortest}" %>

  </div>

  <div class="span1">
    <%= failed_validation_job.run_server %>
  </div>

  <div class="span1 no-wrap" >
    <%= failed_validation_job.start_time.strftime("%d-%m-%y %H:%M") if failed_validation_job.start_time %>&nbsp;
  </div>

  <div class="span1 no-wrap">
    <%= failed_validation_job.finish_time.strftime("%d-%m-%y %H:%M") if failed_validation_job.finish_time %>&nbsp;
  </div>
</div>

<script type="text/javascript">
  $("[id^=chk-]").change(function(){
  toggleButton(this);
  });
</script>

webmis/app/views/validation_jobs/_validation_job.html.erb
<div class="row" id="row_show_<%= validation_job.id %>">
  <div class="span1">
    <div class="btn-group">
      <%= conversion_database_action_link(validation_job) %>
      <ul class="dropdown-menu">
        <li>
          <%= link_to(validation_job) do %>
          <i class="icon-info-sign"></i>&nbsp;show
          <% end %>
        </li>
        <% if validation_job.allow_edit? %>
        <li>
          <%= link_to(edit_validation_job_path(validation_job)) do %>
          <i class="icon-edit"></i>&nbsp;edit
          <%  end %>
        </li>
        <% end %>
        <% if validation_job.allow_reschedule? && !validation_job.allow_edit? %>
        <li>
          <%= link_to edit_new_copy_validation_job_path(validation_job), :method => :post do %>
          <i class="icon-edit"></i>&nbsp;edit new copy
          <% end %>
        </li>
        <% end %>
        <% if validation_job.allow_cancel? %>
          <li>
            <%= link_to cancel_validation_job_path(validation_job, {:lock_version => validation_job.lock_version.to_s}), :method => :post  do %>
            <i class="icon-off"></i>&nbsp;cancel
            <%  end %>
          </li>
         <% end  %>
      </ul>
    </div>
  </div>

  <div class="span1">
    <%= validation_job.id %>
  </div>

  <div class="span2">
    <%= validation_job.status_str %>
  </div>

  <div class="span4">
    <%= link_to conversion_database_path(validation_job.conversion_database.id),:target => '_blank' do %>
      <%= "#{validation_job.conversion_database.id} | #{validation_job.conversion_database.shortest}" %>
    <% end %>
  </div>

  <div class="span1">
    <%= validation_job.run_server %>
  </div>

  <div class="span1 no-wrap" >
    <%= validation_job.start_time.strftime("%d-%m-%y %H:%M") if validation_job.start_time %>&nbsp;
  </div>

  <div class="span1 no-wrap">
    <%= validation_job.finish_time.strftime("%d-%m-%y %H:%M") if validation_job.finish_time %>&nbsp;
  </div>
</div>

webmis/app/views/validation_jobs/edit.html.erb
<% @heading = "Editing validation job " + @validation_job.id.to_s %>
<%= render 'form' %>

<div class="row">
  <div class="span8">
    <%= link_to :back, :class => 'btn', :title => 'back' do %>  
      <i class="icon-arrow-left"></i>
    <% end %>
    <%= link_to validation_jobs_path, :class => 'btn', :title => 'overview' do %>
      <i class="icon-arrow-up"></i>
    <% end %>
    <%= link_to @validation_job, :class => 'btn', :title => 'show' do %>
      <i class="icon-eye-open"></i>
    <% end %>
  </div>
</div>

webmis/app/views/validation_jobs/failures.html.erb
<div class="navbar secondnav">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand"><strong>Tagging Failed validation jobs</strong></div>
      <div class="span">
          <%= form_tag url_for(:action=>:failures), method: 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <div class="input-append">
          <%= select_tag "job_fail_reason", options_for_select(JobFailReason.where(:job_type => @validation_jobs.last.class.name).collect{|f|f.reason}),{:include_blank => true,:data=>{:placeholder => "Assign fail reason"}} %>
            <button type="button" class="btn btn-danger" id="tagSelected" disabled="disabled">Tag selected</button>
         </div>
         <% end %>
     </div>
   </div>
 </div>
</div>
  <fieldset>
<div id="endless">
  
  <div class="row">
    <div class="span1"><strong>check all</strong><input type="checkbox" class="checkall pull-right"/></div>
    <div class="span1"><strong><%=  sortable "id" %></strong></div>
    <div class="span2"><strong><%= sortable "status","Status" %></strong></div>
    <div class="span4"><strong><%= sortable "conversion_databases.path_and_file","Conversion database" %></strong></div>
    <div class="span1"><strong><%= sortable "run_server","Server" %></strong></div>
    <div class="span1"><strong><%= sortable "start_time","Started" %></strong></div>
    <div class="span1"><strong><%= sortable "finish_time", 'Finished' %></strong></div>
  </div>

  <%= render(partial: "failed_validation_job", collection: @validation_jobs) %>

</div>
  </fieldset>
<%= will_paginate(@validation_jobs) %>
<%= pageless(@validation_jobs.total_pages, url_for(:action=>:failures), "#endless", params) %>

<footer class="subnav subnav-fixed" style="bottom:0;top:auto;margin-bottom: 0px;">
  &nbsp;
</footer>

<script type="text/javascript">
  $('#job_fail_reason').chosen({allow_single_deselect:true})

  $(function () {
      $('.checkall').on('click', function () {
          $(this).closest('fieldset').find(':checkbox').prop('checked', this.checked);
          toggleButton($("[id^=chk-]")[0]);
      });
  });

$("#tagSelected").click(function(){
  var allVals = [];
  ($(document)).find("input:checkbox:checked").each(function() {
       allVals.push($(this).val());
     });
  $.post("<%= url_for(:action => :tagging_fail_reason) %>",{'fail_reason':$("#job_fail_reason").val(),'ids[]':allVals});
});


$("[id^=chk-]").change(function(){
toggleButton(this);
});

$("#job_fail_reason").change(function(){
toggleButton($("[id^=chk-]")[0]);
});

function toggleButton(el) {
    if($(el).closest('fieldset').find("input:checkbox:checked").length >= 1 && $("#job_fail_reason").val() != ''){
    $("#tagSelected").removeAttr("disabled");
  }else{
    $("#tagSelected").attr("disabled", "disabled");
  }
}
</script>

webmis/app/views/validation_jobs/index.html.erb
<div class="navbar secondnav">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand"><strong>Validation Jobs</strong></div>
      <div class="span">
        <%= form_tag validation_jobs_path, method: 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <div class="input-prepend input-append">
            <%= select_tag("search_status", options_for_select(ValidationJob.status_hash,params[:search_status]), include_blank: true, class: 'span2', data: {placeholder: 'Status'}) %>
            <%= text_field_tag :search, params[:search], placeholder: " search", class: "span3", size: "16" %>
            <%= button_tag "Search", name: nil, type: :submit, class: "btn" %>
            <%= button_tag "Reset", name: 'reset',class: "btn", type: :submit %>
          </div>
          <% end %>
       </div>
    </div>
  </div>
</div>

<div id="endless">
  <div class="row">
    <div class="offset1 span1"><strong><%=  sortable "id" %></strong></div>
    <div class="span2"><strong><%= sortable "status","Status" %></strong></div>
    <div class="span4"><strong><%= sortable "conversion_databases.path_and_file","Conversion database" %></strong></div>
    <div class="span1"><strong><%= sortable "run_server","Server" %></strong></div>
    <div class="span1"><strong><%= sortable "start_time","Started" %></strong></div>
    <div class="span1"><strong><%= sortable "finish_time", 'Finished' %></strong></div>
  </div>

  <%= render(partial: "validation_job", collection: @validation_jobs) %>
</div>

<%= will_paginate(@validation_jobs) %>
<%= pageless(@validation_jobs.total_pages, validation_jobs_path, "#endless", params) %>

<footer class="subnav subnav-fixed" style="bottom:0;top:auto;margin-bottom: 0px;">
  &nbsp;
</footer>

<script type="text/javascript">
  $('#search_status').chosen({allow_single_deselect:true})
</script>

webmis/app/views/validation_jobs/index.js.erb
$('#endless').html('<%= escape_javascript(render("validation_job")) %>');

webmis/app/views/validation_jobs/new.html.erb
<% @heading = "New Validation Job" %>
<%= render 'form' %>
<div class="row">
  <div class="span10">
    <%= link_to :back, :class => 'btn', :title => 'back' do %>
      <i class="icon-arrow-left"></i>
    <% end %>
    <%= link_to validation_jobs_path, :class => 'btn', :title => 'overview' do %>
      <i class="icon-arrow-up"></i>
    <% end %>
  </div>
</div>

webmis/app/views/validation_jobs/show.html.erb
<div class="modal hide fade extra-large" id="action-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4><%= @validation_job.working_dir  %></h4>
  </div>
</div>

<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span2">Status &nbsp;<span class="label label-info"><%= @validation_job.status_str %></span></div>
      <% if @validation_job.original_job  %>
        <div class="span2">Original job&nbsp;<%= link_to @validation_job.original_job_id, validation_job_path(@validation_job.original_job) %></div>
      <% end %>
      <% if @validation_job.derived_job  %>
        <div class="span2">Derived job&nbsp;<%= link_to @validation_job.derived_job.id, validation_job_path(@validation_job.derived_job) %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span3"><h4>Validation job <%= @validation_job.id %></h4></div>
</div>

<% if !@validation_job.fail_reason.blank? %>
  <div class="row">

    <div class="alert alert-error span12" style="padding-right: 0px">
      <button type="button" class="close" data-dismiss="alert" style="right: 5px;top: -5px">&times;</button>
      <strong>Fail reason</strong><br />
      <%= @validation_job.fail_reason %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="span12 bounded well-small">
    <div class="row">
      <div class="span2"><strong>Conversion database ID</strong></div>
      <div class="span10"><strong>Filename</strong></div>
    </div>
    <div class="row">
      <div class="span2">
        <%= link_to edit_conversion_database_path(@validation_job.conversion_database.id, {:target => '_blank'}) do %>
          <%= @validation_job.conversion_database.id %>
        <% end %>&nbsp;
      </div>
      <div class="span10"><%= @validation_job.conversion_database.path_and_file %>&nbsp;</div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
      <div class="span2"><strong>Server</strong></div>
      <div class="span2"><strong>Process ID (PID)</strong></div>
      <div class="span8"><strong>Run command</strong></div>
    </div>
    <div class="row">
      <div class="span2"><%= @validation_job.run_server %>&nbsp;</div>
      <div class="span2"><%= @validation_job.run_pid %>&nbsp;</div>
      <div class="span8"><%= @validation_job.run_command %>&nbsp;</div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
      <div class="span2"><strong>Exit code</strong></div>
      <div class="span2"><strong>Started at</strong></div>
      <div class="span2"><strong>Finished at</strong></div>
      <div class="span6"><strong>Work directory</strong></div>
    </div>
    <div class="row">
      <div class="span2"><%= @validation_job.exitcode %>&nbsp;</div>
      <div class="span2"><%= @validation_job.start_time.localtime.strftime("%d %b %Y %T") if @validation_job.start_time %>&nbsp;</div>
      <div class="span2"><%= @validation_job.finish_time.localtime.strftime("%d %b %Y %T") if @validation_job.finish_time %>&nbsp;</div>
      <div class="span6"><%= @validation_job.working_dir %>&nbsp;</div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
      <div class="span3 well well-small">
        <div class="row">
          <div class="span2"><strong>Schedule options</strong></div>
        </div>
        <div class="row">
          <div class="span2"><small>Cores&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= @validation_job.schedule_cores %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Memory&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= @validation_job.schedule_memory %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Disk&nbsp;space&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= @validation_job.schedule_diskspace %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Manual&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= bootstrap_boolean(@validation_job.schedule_manual) %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Exclusive&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= bootstrap_boolean(@validation_job.schedule_exclusive) %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Virtual&nbsp;scheduled:</small></div>
          <div class="span1"><small><%= bootstrap_boolean(@validation_job.schedule_allow_virtual,'Allow virtual scheduling ?') %></small></div>
        </div>
        <div class="row">
          <div class="span2"><small>Estimated duration:</small></div>
          <div class="span1">
            <small>
              <% if  @validation_job.estimated_duration && @validation_job.estimated_duration > 0 %>
                <%= distance_of_time_in_words(Time.at(0), Time.at(@validation_job.estimated_duration * 60)) %>
              <% else %>
                Not known
              <% end %>
            </small>
          </div>
        </div>
      </div>

      <div class="span9 pull-right" style="max-width: 850px">
        <pre class="pre-scrollable" style="height: 163px">
          <%= @validation_job.stdout_log %>
        </pre>
      </div>
    </div>

    <div class="row">
      <div class="span12"><strong>Script</strong>
        <pre class="pre-scrollable"><%= @validation_job.job_script ? @validation_job.job_script.to_script("VALIDATION_JOB_ID", @validation_job.id) : @validation_job.run_script %></pre>
      </div>
    </div>

    <br />
    <div class="row">
      <div class="span11">
        <%= link_to 'Cancel Job', cancel_validation_job_path(@validation_job,  :lock_version => @validation_job.lock_version), :class => 'btn btn-small disabled',:id => 'vj_cancel', :method => :post %>

        <%= link_to 'Clean working dir', clean_working_dir_validation_job_path(@validation_job), :class => 'btn btn-small disabled', :method => :post, :id => "vj_clean_working_dir" %>

        <%= link_to 'Edit new copy', edit_new_copy_validation_job_path(@validation_job), :class => 'btn btn-small disabled', :method => :post, :id => "vj_edit_new_copy" %>

        <%= link_to 'Reschedule', reschedule_validation_job_path(@validation_job, :lock_version => @validation_job.lock_version), :class => 'btn btn-small disabled', :method=> :post, :id => "vj_reschedule" %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= link_to :back, :class => 'btn',:title => 'back' do %>
      <i class="icon-arrow-left"></i>
    <% end %>
    <%= link_to validation_jobs_path,:class => 'btn', :title => 'overview' do %>
      <i class="icon-arrow-up"></i>
    <% end %>
    <% if @validation_job.allow_edit? %>
      <%= link_to edit_validation_job_path(@validation_job),{:class => 'btn', :title => 'edit'} do %>
        <i class="icon-edit"></i>
      <% end %>
    <% end %>
    <a class="accordion-toggle btn" data-toggle="collapse" data-parent="#accordion2" href="#collapseLog" id="action-log">
      <i class="icon icon-list" title="Action log"></i>
    </a>
    <a class="accordion-toggle btn" data-toggle="collapse" data-parent="#accordion3" href="#collapseScheduleLog" id="scheduler-log">
      <i class="icon icon-hdd" title="Scheduler log"></i>
    </a>

    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
    <div id="collapseScheduleLog" class="accordion-body collapse">
      <div class="accordion-inner">
        <strong>Scheduler log</strong>
        <pre class="real-pre"><%= @validation_job.scheduler_log %></pre>
      </div>
    </div>
    <div id="collapseLog" class="accordion-body collapse">
      <div class="accordion-inner">
        <strong>Action log</strong>
        <pre class="real-pre"><%=  @validation_job.action_log %></pre>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
<% if @validation_job.allow_cancel? %>
    $('#vj_cancel').removeClass("disabled");
<% end %>
<% if @validation_job.allow_cleanup? %>
    $('#vj_move_to_crashed').removeClass("disabled");
    $('#vj_clean_working_dir').removeClass("disabled");
<% end %>
<% if @validation_job.allow_reschedule? && !@validation_job.allow_edit? %>
    $('#vj_edit_new_copy').removeClass("disabled");
    $('#vj_reschedule').removeClass("disabled");
<% end %>

  $('a.disabled').click(function(e) {
    // Disable links for disabled buttons
    e.preventDefault();
    return false
  });

  $("#collapseScheduleLog").on('shown', function() {
    $('html, body').animate({scrollTop:$(document).height()}, 'slow');
    return false;
  })
</script>

webmis/app/views/validation_jobs/tagging_fail_reason.js.erb
<%  @success_rows.each do |row| %>
  $("#row-"+<%= row %>).fadeOut(1300, function(){
    $(this).remove();
    $('#job_fail_reason').val("").trigger("liszt:updated");
    toggleButton($("[id^=chk-]")[0]);
  });
<% end %>