webmis/config/routes.rb
      get :show_validation_errors, :on => :collection
      post :handle_validation_errors, :on => :collection
      post :close_validation_errors, :on => :collection
      get :patch_requests_report, :on => :collection
      post :change_year_patch_requests_report, :on => :collection
      get :conversions_for_select, :on => :collection
      get :fill_cloned_attributes, :on => :collection
      member do
        get 'handle'
        get 'report'
        get 'mail'
        post :toggle_mark_for_removal
        get 'tpd'
        get 'to_remove'
        get 'favorite'
        get 'remove_tag'
        get 'reset_outcome'
        get 'fill_marking_for_removal_modal_confirm'
        post 'restart_failed_and_crashed_conversion_jobs'
        post 'toggle_outcome_persistence'
        get :new_patch_request
        get :edit_result
        post :update_result
      end
    end
    resources :config_parameters
    resources :conversion_environments do
      member do
        get :toggle_active_yn
      end
    end
    resources :conversiontools do
      post :sync, :on => :collection
      member do
        post :toggle_isactive
      end
    end
    resources :continents do
      get :generate_dakota_id, :on => :collection
    end
    resources :countries do
      post 'redirect_to_index', :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :country_conversion_productsets
    resources :customer_depots
    resources :cvtool_bundles do
      get :get_cvtool_bundles, :on => :collection
      member do
        post :toggle_active_yn
      end
    end
    resources :cvtool_templates do
      member do
        post :upload_script
        get :sendscript
      end
    end
    resources :dashboard_grid_widgets do
      post :save_position, :on => :collection
    end
    resources :dashboard_widgets do
      get :render_widget, :on => :collection
      get :widget_demo_01, :on => :collection
      get :widget_demo_02, :on => :collection
      get :widget_demo_03, :on => :collection
      get :widget_demo_04, :on => :collection
      member do
        
        get :drop_widget_from_grid
      end
    end
    resources :dashboard_grids do
      get :my_dashboards, :on => :collection
      member do
        get :unused_widgets
      end
    end
    resources :data_media
    resources :data_releases do
      member do
        get :render_prev_data_releases
      end
    end
    resources :data_sets do
      post :filling_for_data_type, :on => :collection
      post :release_for_company_abbr, :on => :collection
      post :update_coverage_regions_list_view, :on => :collection
      get :receptions_for_select, :on => :collection
      post :get_split_by_key, :on => :collection
      get :render_regions_for_input, :on => :collection
      member do
        get :handle
        post :change_status
        get :clone
        put :duplicate
        patch :duplicate
        post :add_to_group
        post :remove_from_group
        post :create_group
        get :check_production_order
        post :checked_production_order
        post :create_production_order
        get :edit_process_data_elements
        get :browse_directory
        post :save_process_data_element
        post :remove_process_data_element
        post :save_process_data_element_action_log
        post :save_poi_mapping_layout
        post :sync_with_directory_structure
        get :validate_structure
        get :element_counter
        get :show_process_data_elements
        get :download_file
        get :render_data_set_pre_selection
        post :request_review
        post :review_result
        get :in_use_orders
        get :show_jobs_modal
      end
    end
    resources :data_set_groups do
      post :release_for_company_abbr, :on => :collection
      post :filling_for_data_type, :on => :collection
      member do
        get :handle
        post :remove
        post :restore
        get :clone
        get :check_production_order
      end
    end
    resources :data_types do
      post 'add_filling_to_list', :on => :collection
      post 'remove_filling_from_list', :on => :collection
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :data_type_versions
    resources :default_content_release_notes do
      get 'ranking', :on => :collection
      member do
        get :rank_it
      end
    end
    resources :distribution_list_members
    resources :distribution_lists do
      member do
        get 'delete_y'
        get 'select_new_hard_copies'
      end
    end
    resources :documents do
      post :create_from_external_controller, :on => :collection
      member do
        get 'download'
        get 'select'
        get :delete
      end
    end
    resources :external_contacts do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :file_transfer_accounts do
      get 'new'
      member do
        get 'new'

      end
    end
    resources :fillings do
      member do
        get 'handle'
        post 'remove'
        post 'restore'
        post 'deactivate'
        post 'activate'
      end
    end
    resources :high_level_boms do
      get 'get_product_locations', :on => :collection
      member do

      end
    end
    resources :inbound_orderlines
    resources :invoices do
      member do
        post :invoice
        post :paid
        get :print
        get :credit_invoice
      end
    end
    resources :job_fail_reasons
    resources :jobs do
      get :tagged_failed_jobs_report, :on => :collection
    end
    resources :licenses
    resources :locations
    resources :main do
      get  'routes', :on => :collection
      get  'archive', :on => :collection
      get  'administration', :on => :collection
      get  'shipping', :on => :collection
      get  'portfolio', :on => :collection
      get  'denied', :on => :collection
      post 'searchit', :on => :collection
      get 'searchit', :on => :collection
      get 'change_project', :on => :collection
      get :get_json_file_tree , :on => :collection
      member do
        get 'receptions_admin'
        get 'media_admin'
      end
    end
    resources :mail_conditions
    resources :mail_events do
      member do
        get 'show_sub'
      end
    end
    resources :ordertypes do
      get 'access_control', :on => :collection
      member do
        get 'edit_workflow'
        get 'clone'
        post 'change_status'
      end
    end
    resources :outbound_orderlines do
      member do
        get 'destroy_line'
        get 'report'
      end
    end
    resources :outbound_orders do
      get 'link', :on => :collection
      get 'release_notes_request', :on => :collection
      post 'send_release_notes_request', :on => :collection
      get 'get_products_for_request', :on => :collection
      get 'create_from_order', :on => :collection
      member do
        get 'clone_line'
        get 'html2pdf_slip'
        get 'ordr_lines'
        get 'get_order_lines_mediums'
        get 'get_order_lines_products'
        get 'get_order_lines_manually'
        get :edit_packing
        get :delete_me
        get :show_release_mail
        get :send_bulk_release_mail
        get :send_release_mail
        get :send_release_mail_to_self
        post :cancel_packing
        post :update_packing
      end
    end
    resources :customer_contents do
      member do
        get "render_value"
      end
    end
    resources :customer_content_definitions
    resources :customer_content_specifications do
      post :customer_content_values, :on => :collection
      post :create, :on => :collection
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :customer_content_specification_versions

    resources :customer_content_values do
      member do
        get "render_content"
      end
    end
    resources :customer_targets
    resources :product_lines do
      post :parameters, :on => :collection
      get  :customer_content_definitions, :on => :collection

      post :update_project_members_list, :on => :collection
      member do
        post :customer_content_definitions
        
      end
    end

    resources :packing_jobs do
      get :failures, :on => :collection
      post :tagging_fail_reason, :on => :collection
      member do
        post :cancel
        post :clean_working_dir
        post :edit_new_copy
        post :regenerate
        post :reschedule
        get :cancel
      end
    end
    resources :packing_specifications do
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :packing_specification_versions

    resources :poi_mappings do
      get :content_filter, :on => :collection
      get :details, :on => :collection
      member do
        get :details
      end
    end
    resources :poi_mapping_layouts do
      get :upload_new, :on => :collection
      get :upload_create, :on => :collection
      post :upload_create, :on => :collection
      member do
        get :export_csv
      end
    end
    resources :points
    resources :process_data do
      get :receptions_for_select, :on => :collection
      get :get_data_releases_by_supplier_name, :on => :collection
      get :render_modal_edit_element, :on => :collection
      get :render_modal_edit_log, :on => :collection
      post :cancel_extract_job, :on => :collection
      get :sync_file_structure, :on => :collection
      get :delete_process_data_element, :on => :collection

webmis/app/views/layouts/_flash_on_demand.html.erb
<div id="jsFlash" style="margin-top: 10px;float:right;margin-right: 0px;position:absolute;right:0px;z-index: 9" class="span4 alert alert-block" data-dismiss="alert">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <h4 class="alert-heading" id="jsFlashHeader">Flash on demand</h4>
  <div id="jsFlashContent">Custom content</div>
</div>

webmis/app/views/layouts/_menu.html.erb
<% puts "#####" + Rails.env.to_s %>




<%  if Rails.env == "staging" %>
  <div style="background-color:yellow;text-align: center" ><b>TEST ENVIRONMENT</b><hr/></div>
<% end  %>
<%  if Rails.env == "development" %>
  <div style="background-color:chartreuse;text-align: center"><b>DEVELOPMENT ENVIRONMENT</b><hr/></div>
<% else %>

<% end  %>
  
<div class="ui-tabs ui-widget  " style="font-size: 0.9em;">


</div>
  

webmis/app/views/layouts/_menu_conversion.html.erb
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#" id="conversion">
    Conversion
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to(conversions_path) do %>
        <i class="icon-question-sign"></i>&nbsp;Requests overview
      <% end %>
    </li>
    <li>
      <%= link_to(conversion_jobs_path) do %>
        <i class="icon-qrcode"></i>&nbsp;Conversion jobs overview
      <% end %>
    </li>
    <li>
      <%= link_to(validation_jobs_path) do %>
        <i class="icon-zoom-in"></i>&nbsp;Validation jobs overview
      <% end %>
    </li>
    <li>
      <%= link_to(patch_requests_report_conversions_path) do %>
        <i class="icon-adjust"></i>&nbsp;Patch requests report
      <% end %>
    </li>
    <li>
      <%= link_to(show_validation_errors_conversions_path) do %>
        <i class="icon-exclamation-sign"></i>&nbsp;Validation errors overview
      <% end %>
    </li>
    <li>
      <%= link_to(conversion_databases_path) do %>
        <i class="icon-file"></i>&nbsp;Databases overview
      <% end %>
    </li>
    <li>
      <%= link_to(:action => 'overview', :controller => 'servers', :project_id => session[:project_id]) do %>
        <i class="icon-th-list"></i>&nbsp;Server overview
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'conversion_jobs') do %>
      <i class="icon icon-tags">&nbsp;</i>Tagging failed conversion jobs
      <% end %>
    </li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'validation_jobs') do %>
      <i class="icon icon-tags">&nbsp;</i>Tagging failed validation jobs
      <% end %>
    </li>
    <li>
      <%= link_to(:controller => :conversion_databases,:action => :index,:removal_index => "true" ) do %>
        <i class="icon  icon-map-marker">&nbsp;</i>Mark databases for removal
      <% end %>
    </li>
    <% if env_production? %>
    <li class="divider"></li>
    <li>
      <%= link_to(:action => :new, :controller => :conversions) do %>
        <i class="icon  icon-plus-sign">&nbsp;</i>New conversion-request
      <% end %>
    </li>
    <li>
      <%= link_to(:action => :new_request, :controller => :stock) do %>
        <i class="icon  icon-plus-sign">&nbsp;</i>New medium-request
      <% end %>
    </li>
    <% end %>
    <li class="divider"></li>
    <% if env_production? %>
    <li><%= link_to(assembly_headers_path ) do%>
        <i class="icon-wrench"></i>&nbsp;Assemblies
      <% end %>
    </li>
    <% end %>
    <li><%= link_to(poi_mapping_layouts_path ) do%>
        <i class="icon-camera"></i>&nbsp;POI Mapping Layouts
      <% end %>
    </li>
    <% if env_production? %>
    <li>
      <%= link_to(:controller => :assembly_headers, :action => :new ) do%>
        <i class="icon-wrench"></i>&nbsp;New assembly
      <% end %>
    </li>
    <% end %>
    <li><%= link_to(conversiontools_path ) do%>
        <i class="icon-wrench"></i>&nbsp;Conversion tools
      <% end %>
    </li>
    <li><%= link_to(cvtool_bundles_path ) do%>
        <i class="icon-wrench"></i>&nbsp;Conversion tool bundles
      <% end %>
    </li>
    <li><%= link_to(conversion_environments_path ) do%>
        <i class="icon-wrench"></i>&nbsp;Conversion environments
      <% end %>
    </li>
    <% if env_production? %>
    <li><%= link_to(cvtool_templates_path ) do%>
        <i class="icon-wrench"></i>&nbsp;Conversion templates
      <% end %>
    </li>
    <% end %>
    <li><%= link_to(:action => :marked_for_removal_index, :controller => :conversion_databases) do%>
        <i class="icon-trash"></i>&nbsp;Database cleanup
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_menu_my_settings.html.erb
<li class="dropdown" id="mine">
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#">
    My settings
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to(:controller => 'logout', :action => :index) do %>
        <i class="icon icon-off">&nbsp;</i>Logout
      <% end %>
    </li>
    <li class="divider"></li>
    <% current_dashboards.each do |dashboard| %>
      <li><%= link_to(dashboard) do %>
          <i class="icon-th"></i>&nbsp;<%= dashboard.name %>
        <% end %>
      </li>
    <% end %>
    <li><%= link_to(:action => :my_dashboards,:controller => :dashboard_grids) do %>
        <i class="icon-th-large"></i>&nbsp;Dashboard control
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_menu_shipping.html.erb
<li class="dropdown" >
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#" id="shipping">
    Shipping
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to(outbound_orders_path) do  %>
        <i class="icon icon-road">&nbsp;</i>Shipments
      <% end %>
    </li>
    <li>
      <%= link_to(:action => :mastering_index, :controller => :production_orderlines) do %>
        <i class="icon icon-question-sign">&nbsp;</i>Mastering requests
      <% end %>
    </li>
    <li>
      <%= link_to(:action => :shipment_index, :controller => :production_orderlines) do %>
        <i class="icon icon-question-sign">&nbsp;</i>Shipment requests
      <% end %>
    </li>
    <li>
        <%= link_to(distribution_lists_path) do  %>
          <i class="icon icon-envelope">&nbsp;</i>Distribution lists
        <% end %>
    </li>
    <li>
      <%= link_to(packing_jobs_path) do %>
        <i class="icon icon-gift">&nbsp;</i>Packing jobs overview
      <% end %>
    </li>
    <li>
      <%= link_to(shipping_jobs_path) do %>
        <i class="icon icon-gift">&nbsp;</i>Shipping jobs overview
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'packing_jobs') do %>
      <i class="icon icon-tags">&nbsp;</i>Tagging failed packing jobs
      <% end %>
    </li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'shipping_jobs') do %>
        <i class="icon icon-tags">&nbsp;</i>Tagging failed shipping jobs
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(companies_path) do  %>
        <i class="icon  icon-home">&nbsp;</i>Companies
      <% end %>
    </li>
    <li>
      <%= link_to(external_contacts_path) do  %>
        <i class="icon icon-user">&nbsp;</i>External contacts
      <% end %>
    </li>
    <li>
      <%= link_to(new_distribution_list_path) do %>
        <i class="icon-wrench"></i>&nbsp;New distribution list
      <% end %>
    </li>
    <li>
      <%= link_to(shipment_types_path) do %>
        <i class="icon-wrench"></i>&nbsp;Shipment types
      <% end %>
    </li>
    <li>
      <%= link_to(outbound_orderlines_path) do %>
        <i class="icon-th-list"></i>&nbsp;Product shipment list
      <% end %>
    </li>
    <li>
      <%= link_to '/webmis/delayed_job', :target => "_blank" do %>
        <i class="icon-wrench"></i>&nbsp;Delayed Job Overview
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_menu_testing.erb
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#" id="testing">
    Testing
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to(test_requests_path) do %>
        <i class="icon-zoom-in"></i>&nbsp;Requests overview
      <% end %>
    </li>
    <li>
      <%= link_to(:action => 'requests', :controller => 'stock') do %>
        <i class="icon-fire"></i>&nbsp;Medium requests
      <% end %>
    </li>
    <li>
      <%= link_to(test_request_jobs_path) do %>
        <i class="icon-qrcode"></i>&nbsp;Test request jobs overview
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(:action => :new, :controller => :test_requests) do %>
        <i class="icon-plus-sign"></i>&nbsp;New test-request
      <% end %>
    </li>
    <li class="divider">Admin</li>
    <li>
      <%= link_to test_plans_path,:title => "test plans" do %>
        <i class="icon-wrench"></i>&nbsp;Test plans
      <% end %>
    </li>
    <li><%= link_to(test_types_path) do %>
        <i class="icon-wrench"></i>&nbsp;Test types
      <% end %>
    </li>
    <li><%= link_to(test_tool_releases_path) do %>
        <i class="icon-wrench"></i>&nbsp;Test tool releases
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_navbar_design.html.erb
<li class="dropdown" id="configuration">
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#">
    Design
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to(product_designs_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Product Designs
      <% end %>
    </li>
    <li><%= link_to(product_features_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Product Features
      <% end %>
    </li>
    <li><%= link_to(executables_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Executables
      <% end %>
    </li>
    <li><%= link_to(parameter_settings_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Parameter Settings
      <% end %>
    </li>
    <% if env_production? %>
    <li><%= link_to(design_tags_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Design Tags
      <% end %>
    </li>
    <% end %>
    <li><%= link_to(api_logs_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;API Log
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_navbar_my_settings.html.erb
<li class="dropdown" id="mine">
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#">
    My settings
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to(:controller => 'logout', :action => :index) do %>
        <span class="icon glyphicon glyphicon-off">&nbsp;</span>Logout
      <% end %>
    </li>
    <li class="divider"></li>
    <% current_dashboards.each do |dashboard| %>
      <li><%= link_to(dashboard) do %>
          <span class="glyphicon glyphicon-th"></span>&nbsp;<%= dashboard.name %>
        <% end %>
      </li>
    <% end %>
    <li><%= link_to(:action => :my_dashboards,:controller => :dashboard_grids) do %>
        <span class="glyphicon glyphicon-th-large"></span>&nbsp;Dashboard control
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/_navbar_shipping.html.erb
<li class="dropdown" >
  <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="#" id="shipping">
    Shipping
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to(outbound_orders_path) do  %>
        <span class="icon glyphicon glyphicon-road">&nbsp;</span>Shipments
      <% end %>
    </li>
    <li>
      <%= link_to(:action => :mastering_index, :controller => :production_orderlines) do %>
        <span class="icon glyphicon glyphicon-question-sign">&nbsp;</span>Mastering requests
      <% end %>
    </li>
    <li>
      <%= link_to(:action => :shipment_index, :controller => :production_orderlines) do %>
        <span class="icon glyphicon glyphicon-question-sign">&nbsp;</span>Shipment requests
      <% end %>
    </li>
    <li>
        <%= link_to(distribution_lists_path) do  %>
          <span class="icon glyphicon glyphicon-envelope">&nbsp;</span>Distribution lists
        <% end %>
    </li>
    <li>
      <%= link_to(packing_jobs_path) do %>
        <span class="icon glyphicon glyphicon-gift">&nbsp;</span>Packing jobs overview
      <% end %>
    </li>
    <li>
      <%= link_to(shipping_jobs_path) do %>
        <span class="icon glyphicon glyphicon-gift">&nbsp;</span>Shipping jobs overview
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'packing_jobs') do %>
      <span class="icon glyphicon glyphicon-tags">&nbsp;</span>Tagging failed packing jobs
      <% end %>
    </li>
    <li>
      <%= link_to(:action => 'failures', :controller => 'shipping_jobs') do %>
        <span class="icon glyphicon glyphicon-tags">&nbsp;</span>Tagging failed shipping jobs
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to(companies_path) do  %>
        <span class="icon  glyphicon glyphicon-home">&nbsp;</span>Companies
      <% end %>
    </li>
    <li>
      <%= link_to(external_contacts_path) do  %>
        <span class="icon glyphicon glyphicon-user">&nbsp;</span>External contacts
      <% end %>
    </li>
    <li>
      <%= link_to(new_distribution_list_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;New distribution list
      <% end %>
    </li>
    <li>
      <%= link_to(shipment_types_path) do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Shipment types
      <% end %>
    </li>
    <li>
      <%= link_to(outbound_orderlines_path) do %>
        <span class="glyphicon glyphicon-th-list"></span>&nbsp;Product shipment list
      <% end %>
    </li>
    <li>
      <%= link_to '/webmis/delayed_job', :target => "_blank" do %>
        <span class="glyphicon glyphicon-wrench"></span>&nbsp;Delayed Job Overview
      <% end %>
    </li>
  </ul>
</li>

webmis/app/views/layouts/general.html.erb
<html>
  <head>
        <%= csrf_meta_tag %>
    <style type="text/css"> 
      /* Special for firefox => Prevent dotted border afgter click */
      .ui-tabs .ui-tabs-nav li a {
        outline: 0;
        float: left;
        padding: .5em 1em;
        text-decoration: none; 
      }
    </style>
    
    <%= javascript_include_tag 'jquery-1.6.2.min.js','jquery-ui-1.8.16.custom.min.js' %>
    <%= stylesheet_link_tag 'dsm', :media => "all" %>
    <%= stylesheet_link_tag session[:dynamic_css] %>
    <%= stylesheet_link_tag 'backoffice.css' %>
    
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'popup.js' %>
    <%= include_wice_grid_assets %>
    <%= javascript_include_tag 'tooltip2' %>
    <% if @page_title %>
      <title><%= @page_title.to_s %></title>
    <% else %>
      <title><%= controller.controller_name.humanize %>-<%= controller.action_name.humanize -%></title>
    <% end %>
    <%= stylesheet_link_tag 'windowfiles/dhtmlwindow.css', :media => "all"  %>
    <link rel="shortcut icon" href="/webmis/images/favicon.ico" type="image/x-icon" />

    <script type="text/javascript">
      jQuery(document).ready(function() {
        jQuery('.toolTip').hover(
          function() {
          this.tip = this.title;
            jQuery(this).append(
           '<div style="position: absolute;z-index:1;"  id="current-tooltip">'
              +'<div class="ui-state-highlight ui-corner-all" style="padding:5px;margin-left: 10px;">'
                +this.tip
              +'</div>'
            +'</div>'
          );
          this.title = "";
          this.width = jQuery(this).width();
          jQuery.(this).fadeIn(9900);
        },
          function() {
            jQuery('current-tooltip').fadeOut(1000);
            jQuery(this).children().remove();            
              this.title = this.tip;
            }
        );
      });
    </script>
    
<script type="text/javascript">
	jQuery(function() {
            jQuery('div#button').hover(
		function() { jQuery(this).addClass('ui-state-hover'); }, 
		function() { jQuery(this).removeClass('ui-state-hover'); }
	      );        
        });
</script>    
    
    <SCRIPT LANGUAGE="JavaScript">
      <!--
      function showHide(elementid){
        if (document.getElementById(elementid).style.display == 'none'){
          document.getElementById(elementid).style.display = '';
        } else {
          document.getElementById(elementid).style.display = 'none';
        }
      }

      function showIcon(elementid){
        if (document.getElementById(elementid).style.display == 'none'){
          document.getElementById(elementid).style.display = '';
        }
      }
      //-->

    

function ChgText(elementid,content)
{
    document.getElementById(elementid).value = content;
    document.getElementById(elementid).disabled = false;
    return true;
}
</SCRIPT>

  </head>

  <% if params[:nomenu] %>
    <body class = "nomenu">
    <% else %>
    <body class = "menu">
    <% end %>
    <div id="wrapper" >
      <div id="container">

        <% if !params[:nomenu]%>
          
          
<div style="font-size:0.7em; position:absolute; right:15px;z-index: 999">
  Last deploy time : <%= ENV['last_deploy'] %>&nbsp;
  <%= link_to 'profile', :controller => :users, :action => 'edit_profile', :id => current_user.id %>
</div>

            <%= render :partial => "/layouts/menu" %>

      <% end %>

        <div class="main">
          <div  class="content">
            <% if flash[:notice] %>
              <div id = "notice">
                <%= flash[:notice] %>
              </div>
            <% end %>
            <% if flash[:error] %>
              <div id = "error">
                <%= flash[:error] %>
              </div>
            <% end %>
            
            <%= yield  %>
          </div>
        </div>

      </div>
    </div>
  </body>
</html>