webmis/config/routes.rb
MIS::Application.routes.draw do

  get '404', :to =>"errors#not_found"
  get '500', :to => "errors#internal_server_error"
  
  get '/', to: redirect('/webmis')

  scope '/webmis' do
      

    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    root :to => 'main#index'
    resources :allocation_exceptions
    resources :errors do
      get :not_found, :on => :collection
      get :internal_server_error, :on => :collection
    end
    resources :api_logs

    resources :warehouse_stock_adjustments do
      get :onhand, :on => :collection
      post :onhand, :on => :collection
    end

    resources :areas do
      get :generate_dakota_id, :on => :collection
      member do
      end
    end
    resources :area_types
    resources :articles
    resources :article_licenses do
      get :license_fee_report, :on => :collection
      post :html2pdf_license_fee_po, :on => :collection
    end
    resources :assembly_headers do
      member do
        get 'create_csv'
        get 'cloneit'
        get 'table_edit'
        post 'add_checked'
        post 'destroy_line'
        get 'add_tag4mre'
        get 'remove_mre_tag'
        get 'add_update_region_tag'
        get 'replace_data'
        get 'update_coverage_view_by_map'
      end
    end
    resources :assembly_lines
    resources :assets do
      member do

      end
    end
    resources :asset_type_number_ranges
    resources :asset_types do
      get 'create_number', :on => :collection
      post 'create_number', :on => :collection
      member do

      end
    end
    resources :business_processes
    resources :carin_productsets
    resources :cities do
      post 'redirect_to_index' , :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :commitment_change_reasons
    resources :companies do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :company_abbrs, :tags do
      get :dakota_supplier_ids_file, :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :content_release_notes do
      get :get_versions_and_regions_for_project, :on => :collection
      get :get_jira_release_note, :on => :collection
    end
    resources :conversion_databases do
      get :marked_for_removal_index, :on => :collection
      post :batch_mark_for_removal, :on => :collection
      post :db_remove_script, :on => :collection
      get :download_db_remove_script, :on => :collection
      get :render_file_tree, :on => :collection
      member do
        get :handle
        post :change_status
        get :download_stdout_log
        post :mark_for_removal
        post :unmark_for_removal
      end
    end
    resources :conversion_jobs do
      get :failures, :on => :collection
      post :tagging_fail_reason, :on => :collection
      member do
        post :cancel
        post :clean_working_dir
        post :edit_new_copy
        get :edit_new_copy
        post :handle_crashed
        post :reschedule
        get :tail_z_log
        get :terminal
        get :cancel
        post :generated_script
      end
    end
    resources :conversions, :tags do
      get :check_cvtool, :on => :collection
      get :get_cvtool_bundles, :on => :collection
      get :get_datareleases, :on => :collection
      get :get_datareleases_for_overview, :on => :collection
      get :get_production_orders, :on => :collection
      get :import_assembly , :on => :collection
      get :import_process_data , :on => :collection
      get :get_data_by_pid , :on => :collection
      post :check_cvtool, :on => :collection
      post :allocate_data, :on => :collection
      get :cloneit, :on => :collection
      get :show_validation_errors, :on => :collection
      post :handle_validation_errors, :on => :collection
      post :close_validation_errors, :on => :collection
      get :patch_requests_report, :on => :collection
      post :change_year_patch_requests_report, :on => :collection
      get :conversions_for_select, :on => :collection
      get :fill_cloned_attributes, :on => :collection
      member do
        get 'handle'
        get 'report'
        get 'mail'
        post :toggle_mark_for_removal
        get 'tpd'
        get 'to_remove'
        get 'favorite'
        get 'remove_tag'
        get 'reset_outcome'
        get 'fill_marking_for_removal_modal_confirm'
        post 'restart_failed_and_crashed_conversion_jobs'
        post 'toggle_outcome_persistence'
        get :new_patch_request
        get :edit_result
        post :update_result
      end
    end
    resources :config_parameters
    resources :conversion_environments do
      member do
        get :toggle_active_yn
      end
    end
    resources :conversiontools do
      post :sync, :on => :collection
      member do
        post :toggle_isactive
      end
    end
    resources :continents do
      get :generate_dakota_id, :on => :collection
    end
    resources :countries do
      post 'redirect_to_index', :on => :collection
      get :generate_dakota_id, :on => :collection
    end
    resources :country_conversion_productsets
    resources :customer_depots
    resources :cvtool_bundles do
      get :get_cvtool_bundles, :on => :collection
      member do
        post :toggle_active_yn
      end
    end
    resources :cvtool_templates do
      member do
        post :upload_script
        get :sendscript
      end
    end
    resources :dashboard_grid_widgets do
      post :save_position, :on => :collection
    end
    resources :dashboard_widgets do
      get :render_widget, :on => :collection
      get :widget_demo_01, :on => :collection
      get :widget_demo_02, :on => :collection
      get :widget_demo_03, :on => :collection
      get :widget_demo_04, :on => :collection
      member do
        
        get :drop_widget_from_grid
      end
    end
    resources :dashboard_grids do
      get :my_dashboards, :on => :collection
      member do
        get :unused_widgets
      end
    end
    resources :data_media
    resources :data_releases do
      member do
        get :render_prev_data_releases
      end
    end
    resources :data_sets do
      post :filling_for_data_type, :on => :collection
      post :release_for_company_abbr, :on => :collection
      post :update_coverage_regions_list_view, :on => :collection
      get :receptions_for_select, :on => :collection
      post :get_split_by_key, :on => :collection
      get :render_regions_for_input, :on => :collection
      member do
        get :handle
        post :change_status
        get :clone
        put :duplicate
        patch :duplicate
        post :add_to_group
        post :remove_from_group
        post :create_group
        get :check_production_order
        post :checked_production_order
        post :create_production_order
        get :edit_process_data_elements
        get :browse_directory
        post :save_process_data_element
        post :remove_process_data_element
        post :save_process_data_element_action_log
        post :save_poi_mapping_layout
        post :sync_with_directory_structure
        get :validate_structure
        get :element_counter
        get :show_process_data_elements
        get :download_file
        get :render_data_set_pre_selection
        post :request_review
        post :review_result
        get :in_use_orders
        get :show_jobs_modal
      end
    end
    resources :data_set_groups do
      post :release_for_company_abbr, :on => :collection
      post :filling_for_data_type, :on => :collection
      member do
        get :handle
        post :remove
        post :restore
        get :clone
        get :check_production_order
      end
    end
    resources :data_types do
      post 'add_filling_to_list', :on => :collection
      post 'remove_filling_from_list', :on => :collection
      member do
        get "handle"
        get "approved"
        post "draft"
        post "review"
        post "approve"
        post "approve_directly"
        post "obsolete"
        post "revert"
      end
    end
    resources :data_type_versions
    resources :default_content_release_notes do
      get 'ranking', :on => :collection
      member do
        get :rank_it
      end
    end
    resources :distribution_list_members
    resources :distribution_lists do
      member do
        get 'delete_y'
        get 'select_new_hard_copies'
      end
    end
    resources :documents do
      post :create_from_external_controller, :on => :collection
      member do
        get 'download'
        get 'select'
        get :delete
      end
    end
    resources :external_contacts do
      member do
        get  :handle
        post :change_status
      end
    end
    resources :file_transfer_accounts do
      get 'new'
      member do
        get 'new'

      end
    end
    resources :fillings do
      member do
        get 'handle'
        post 'remove'
        post 'restore'
        post 'deactivate'
        post 'activate'
      end
    end
    resources :high_level_boms do
      get 'get_product_locations', :on => :collection
      member do

      end
    end
    resources :inbound_orderlines
    resources :invoices do
      member do
        post :invoice
        post :paid
        get :print
        get :credit_invoice
      end
    end
    resources :job_fail_reasons
    resources :jobs do
      get :tagged_failed_jobs_report, :on => :collection
    end
    resources :licenses
    resources :locations
    resources :main do
      get  'routes', :on => :collection
      get  'archive', :on => :collection
      get  'administration', :on => :collection
      get  'shipping', :on => :collection
      get  'portfolio', :on => :collection
      get  'denied', :on => :collection
      post 'searchit', :on => :collection
      get 'searchit', :on => :collection
      get 'change_project', :on => :collection
      get :get_json_file_tree , :on => :collection
      member do

webmis/app/models/data_set_group.rb
class DataSetGroup < ActiveRecord::Base
  validates :company_abbr, :presence => true
  validates :data_release, :presence => true
  validates :region_code,  :presence => true
  
  has_many :data_set_group_lines
  has_many :data_sets, :through => :data_set_group_lines

  STATUS_ACTIVE                 = 500
  STATUS_REMOVED                = 999

  validates :data_release, uniqueness: { :scope => [:company_abbr, :data_type, :filling, :region_code, :suffix],
    :if => :active?, :message => "/ Supplier / Coverage / Data type combination already in use." }
  scope :active, ->  { where(:status => STATUS_ACTIVE)  }
  scope :removed, -> { where(:status => STATUS_REMOVED) }
  
  @@statusarray = Array.new
  @@statusarray[STATUS_ACTIVE]             = 'Active'
  @@statusarray[STATUS_REMOVED]            = 'Removed'
  
  after_initialize :default_values
  
  def status_string
    return @@statusarray[self.status]
  end

  def self.status_array
    @@statusarray.collect{|v|[v,@@statusarray.index(v)]if v}.compact
  end

  def active?
    self.status == STATUS_ACTIVE
  end

  def code
    code_a = []
    code_a << self.company_abbr if !self.company_abbr.blank?
    code_a << self.data_release if !self.data_release.blank? 
    code_a << self.region_code  if !self.region_code.blank?
    if !self.data_type.blank?
      if self.filling.blank?
        code_a << self.data_type
      else
        code_a << "#{self.data_type}[#{self.filling}]"
      end
    end
    code_a << self.suffix  if !self.suffix.blank?
    return !code_a.empty? ? code_a.join('|') : ""
  end

  def name
    self.code.gsub('|',' ').gsub('[',' - ').gsub(']','')
  end
  
  def self.find_by_code(p_company_abbr,p_region_code,p_data_release='latest',p_data_type='*',p_filling=nil,p_suffix=nil)
    conditions = "1=1"
    conditions_string_ary = []
    
    conditions_string_ary << conditions
    conditions_string_ary << "data_set_groups.company_abbr = '#{p_company_abbr}'"
    conditions_string_ary << "data_set_groups.region_code  = '#{p_region_code}'"
    if p_data_release == 'latest'
      # latest already returned by using last ordered on data_release
    else
      conditions_string_ary << "data_set_groups.data_release = '#{p_data_release}'"
    end
    if p_data_type
      conditions_string_ary << "data_set_groups.data_type    = '#{p_data_type}'"
    end
    if p_filling
      conditions_string_ary << "data_set_groups.filling      = '#{p_filling}'"
    end
    if p_suffix
      conditions_string_ary << "data_set_groups.suffix       = '#{p_suffix}'"
    end
    conditions = conditions_string_ary.join(' AND ')
    selection =  DataSetGroup.active.where("#{conditions}").order(:data_release)
    if selection && selection.size > 1 && p_data_type == '*'
      filtered_selection = selection.where( "data_set_groups.data_type IS NULL OR data_set_groups.data_type = ''" )
      if filtered_selection
        return filtered_selection.last
      end
    else
      return selection.last
    end
  end

  def sync_lines(ds_ids=[])
    new_list = ds_ids.sort

    DataSetGroupLine.transaction do
      self.data_sets.each do |ds|
        # Remove unwanted
        if !new_list.include?(ds.id)
          match = self.data_set_group_lines.where(:data_set_id => ds.id)
          match.each do |dsgl|
            dsgl.destroy
          end
        end
        # Keep existing
        if new_list.include?(ds.id)
          new_list.delete_if {|id| id == ds.id }
        end
      end
      # Create remaining as new line
      new_list.each do |ds_id|
        new_line = DataSetGroupLine.new(:data_set_id => ds_id,:data_set_group_id => self.id)
        new_line.save!
      end
    end

  end

  def duplicate
    new_group = self.dup
    DataSetGroupLine.transaction do
      new_group.description = "Cloned from data set group \"#{self.name}\"."
      uniqstr = Digest::SHA1.hexdigest(Time.now.to_s)
      new_group.suffix = new_group.suffix.to_s + "_CLONE_#{uniqstr}" # makes group unique
      new_group.status = STATUS_ACTIVE
      new_group.save!
      self.data_set_group_lines.each do |line|
        new_line = line.dup
        new_line.data_set_group_id = new_group.id
        new_line.save!
      end
    end
    return new_group
  end


  def production_order_allowed?(project_id)
    all_data_sets_size = self.data_sets.size
    if project_id == Project.default.id
      if all_data_sets_size == self.data_sets.where(:status => DataSet::STATUS_PRODUCTION).size
        return true
      end
    else
      if all_data_sets_size == self.data_sets.where("data_sets.status = #{DataSet::STATUS_PRODUCTION} OR data_sets.status = #{DataSet::STATUS_TEST}").size
        return true
      end
    end
    return false
  end
  
  private
    def default_values
      self.status ||= STATUS_ACTIVE
    end  
end

webmis/app/views/data_set_groups/check_production_order.html.erb
<% @submit_str = "Check" %>
<div class="row">
  <div class="span12 bounded bounded-headered">
    <div class="row bounded-header">
      <div class="span7"><h4>Check production order for the data set group <%= @data_set_group.name %></h4></div>
    </div>
    <div class="row">
      <%= form_tag(url_for(:action => :checked_production_order,:controller => :data_sets, :id => @data_set_group.data_sets.first.id),{:id => 'create_order'}) do %>

  <div class="span12">
    <div class="row">
       <div class="span3"><strong>Order type</strong></div>
       <div class="span3"><strong>CV-tool Release</strong></div>
       <div class="span3"><strong>CV-tool Bundle</strong> </div>
       <div class="span3"><strong>CVE</strong></div>
       </div>
    <div class="row">
      <div class="span3"><%= select_tag 'order_type_id', options_for_select(Ordertype.active.where(:is_frontend => true).collect{|ot|["#{ot.name}",ot.id]},params[:order_type_id]),:class => 'span3 validate', :required => 'required' %></div>
      <div class="span3"><%= select_tag 'conversiontool_id', options_for_select(Conversiontool.select_tag,params[:conversiontool_id]),:include_blank => true, :class => 'span3 validate', :required => 'required' %></div>
      <div class="span3" id="cvtool_bundle_div">
        <%= select_tag('cvtool_bundle_id',options_for_select(CvtoolBundle.select_tag,params[:cvtool_bundle_id]),:include_blank => true, :class => 'span3 validate',:required => :required,:data => {:placeholder => 'Select CV tool bundle'}) %>
      </div>
      <input type="hidden" id="fallback_cvtool_bundle_id"></input>
      <div class="span3"><%= select_tag 'conversion_environment_id', options_for_select(ConversionEnvironment.collection_for_select,params[:conversion_environment_id]),:class => 'span3' %></div>
    </div>
    <div class="row">
      <div class="span3"><strong>Test Strategy</strong></div>
      <div class="span3"><strong>Dakota simulator</strong></div>
      <div class="span3"><strong>Use test versions</strong></div>
      <div class="span3"><strong>Product design</strong></div>
    </div>
    <div class="row">
      <div class="span3"><%= select_tag 'test_strategy' , options_for_select(['None', 'All', 'Final Result'], params[:test_strategy]),  :class => 'span3' %></div>
      <div class="span3"><%= check_box_tag 'simulate_dakota', "1",nil,{:data => {"text-label" => "Dakota Sim",:on => "success",:off => "default"}}  %></div>
      <div class="span3"><%= check_box_tag 'use_test_versions_yn', @use_test_versions, @use_test_versions,{:data => {"text-label" => "Test versions",:on => "success",:off => "default"}} %></div>
      <div class="span3"><%= select_tag 'product_design_id', options_for_select(ProductDesign.frontend.where(:project_id => session[:project_id]).option_list,params[:product_design_id]),:class => 'span3 validate',:include_blank => true, :required => 'required' %></div>
    </div>
    <div id="datasets">
    <div class="row">
      <div class="span12">
        <strong>Data sets</strong>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <% @data_set_group.data_sets.includes(:regions).order("regions.name").each do |dataset| %>
           <span class="label" id="Dataset-<%= dataset.id %>">
             <i class="icon-trash" id="delDataset-<%= dataset.id %>" title="remove dataset for processing"></i>
             <%= dataset.label(true) %>&nbsp;&nbsp;
             <input id="field-<%= dataset.id %>" name="datasets[<%= dataset.id %>]" type="hidden" value="<%= dataset.processable_regions.collect{|r|r.region.region_code}.join(',') %>"></input>
           </span>        
        <% end %>
        </div>
    </div>
    </div>
    <div class="row"><br />
      <div class="span5 alert alert-error" id="form-val" style="display: none;"><strong>All fields</strong> are mandatory! Please select an option for the empty fields. </div>
      <div class="span2 pull-right">
        <br /><%= submit_tag "#{@submit_str}",:class => 'btn btn-primary pull-right' %>
        <%= link_to("Reset form",check_production_order_data_set_group_path(@data_set_group),:class => "btn") %>
      </div>
    </div>
  </div>
     <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span1">
    <%= link_to({:action => :index},{:class => 'btn',:title => "Back to data set groups"}) do %>
      <i class="icon icon-arrow-left">&nbsp;</i>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#simulate_dakota").bootstrapSwitch();
  $("#use_test_versions_yn").bootstrapSwitch();
  $(".has-switch").css("min-width", "254px")

  function get_cvtool_bundles(conversiontool_id){
    jQuery.get('<%= url_for get_cvtool_bundles_cvtool_bundles_path %>'+'?conversiontool_id=' + conversiontool_id + "&cvtool_bundle_id=<%= params[:cvtool_bundle_id].to_s %>&tag=cvtool_bundle_id", function(data){
      $("#cvtool_bundle_div").html(data);
      $("#cvtool_bundle_id").select2("val",$("#fallback_cvtool_bundle_id").val());
    })
    return false;
  }

  $("#conversiontool_id").change(function(){
    var selected = $('select#conversiontool_id :selected').val();
    if(selected == "") selected="0";
    get_cvtool_bundles(selected);
  });

  $('#product_design_id').select2({placeholder:"Select product design"});
  $('#order_type_id').select2();
  $('#conversiontool_id').select2({placeholder:"Select CV tool release"});
  $('#test_strategy').select2();

  $('#cvtool_bundle_id').select2();
  $('body').on('change',"#cvtool_bundle_id",function(){
    $("#fallback_cvtool_bundle_id").val($(this).val());
  })

  $("#conversion_environment_id option:first").attr('selected','selected');
  $("#conversion_environment_id").select2();

  $('body').on('click',"[id^=delDataset]",function(){
    var id = $(this).attr('id').match(/\d+/);
    var gsub = "delDataset-" + id + "-"
    var step = $(this).attr('id').replace(gsub,'')
    $("#sel-"+step).select2("destroy");
    $("#sel-"+step)
    .append($("<option></option>")
    .attr("value",id)
    .text($("#Dataset-"+id).text().trim())
  );
    $("#sel-"+step).select2();
    $("#Dataset-"+id).remove();
  });

  <% if @err || params[:error] %>
    $('#form-val').html('<%= @err.to_s + params[:error] %>')
    $('#form-val').fadeIn();
  <% end %>

  $('body').on('hover',"[id^=delDataset-]",function(){
    $(this).css( 'cursor', 'pointer' );
  });

  // When user is using "back" these depended selects needs to be filled again
  $("#conversiontool_id").trigger("change");
   
  var myApp;
  myApp = myApp || (function () {
    var pleaseWaitDiv = $('<div class="modal hide" id="pleaseWaitDialog" data-backdrop="static" data-keyboard="false"><div class="modal-header"><h4>Processing...</h4></div><div class="modal-body"><div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div></div></div>');
    return {
      showPleaseWait: function() {
        pleaseWaitDiv.modal();
      },
      hidePleaseWait: function () {
        pleaseWaitDiv.modal('hide');
      }
    };
  })();

  $("#create_order").submit(function( event ) {
    if ( $("#cvtool_bundle_id").val() == '' ){
      event.preventDefault();
      $('#form-val').html('Fails');
      $('#form-val').fadeIn();
      return false
    }
    myApp.showPleaseWait();
  });
</script>

webmis/app/views/data_set_groups/edit.html.erb
<%= render 'form' %>
<div class="row">
  <div class="span12">
    <%= link_to :back, :class => 'btn',:title => 'back to previous page' do %>
      <i class="icon icon-arrow-left"></i>
    <% end %>
    <%= link_to data_set_groups_path, :class => 'btn',:title => 'back to overview' do %>
      <i class="icon icon-arrow-up"></i>
    <% end %>
    <%= link_to data_set_group_path(@data_set_group),:class => 'btn', :title => "show" do %>
      <i class="icon-eye-open"></i>
    <% end %>
    <%= link_to handle_data_set_group_path(@data_set_group),:class => 'btn', :title => "handle" do %>
      <i class="icon-tasks"></i>
    <% end %>
    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
  </div>
</div>

webmis/app/views/data_set_groups/handle.html.erb
<%= render :partial => 'show_data' %>
<div class="row">
  <div class="span12">
    <% if @data_set_group.status != DataSetGroup::STATUS_REMOVED %>
      <%= link_to remove_data_set_group_path(@data_set_group),:method => :post,:class => 'btn pull-right btn-danger' do %>
        <i class="icon-trash" title="Remove">&nbsp;</i>Remove group
      <% end %>
    <% end %>
    <% if @data_set_group.status == DataSetGroup::STATUS_REMOVED %>
      <%= link_to restore_data_set_group_path(@data_set_group),:method => :post,:class => 'btn pull-right btn-warning' do %>
        <i class="icon-repeat" title="Restore">&nbsp;</i>Restore group
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <%= link_to :back, :class => 'btn',:title => 'back' do %>
      <i class="icon icon-arrow-left"></i>
    <% end %>
    <%= link_to data_set_groups_path, :class => 'btn',:title => 'back',:title => "overview" do %>
      <i class="icon icon-arrow-up"></i>
    <% end %>
    <%= link_to data_set_group_path(@data_set_group),:class => 'btn', :title => "show" do %>
      <i class="icon-eye-open"></i>
    <% end %>
    <%= link_to edit_data_set_group_path(@data_set_group),:class => 'btn',:title => "edit" do %>
      <i class="icon-edit"></i>
    <% end %>
    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
  </div>
</div>

webmis/app/views/data_set_groups/index.html.erb
<div class="navbar secondnav">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand">
        <strong>
          Data set groups
        </strong>
      </div>
        <%= form_tag data_set_groups_path, :method => 'get' do %>
        <div class="span">
          <div class="input-bar">
          <label class="checkbox">
            <%= check_box_tag :removed, "1", @removed,{:data => {"text-label" => "removed","off-label" => "","on-label" => "Include",:size => "normal",:on => "success",:off => "default","off-label" => "excluded"}} %>
          </label>
          </div>
      </div>
      <div class="span">
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <div class="input-prepend input-append">
            <%= link_to("New",new_data_set_group_path,{:class => 'btn btn-info'}) if env_production? %>
            <%= text_field_tag :search, params[:search], :placeholder=>" search" %>
            <%= button_tag "Search", :name => nil, :type => :submit, :class => "btn" %>
            <%= button_tag "Reset", :name => 'reset',:class=>"btn",:type=>:submit %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="endless">
  <div class="row">
    <div class="span1">&nbsp;</div>
    <div class="span0_5"><strong><%= sortable "data_set_groups.id", 'Id',true %></strong></div>
    <div class="span1"><strong><%= sortable "data_set_groups.company_abbr", 'Supplier',true,DataSetGroup.all.collect{|d| [d.company_abbr] if d.company_abbr && d.company_abbr != ''}.uniq.compact.sort %></strong></div>
    <div class="span1"><strong><%= sortable "data_set_groups.data_release", 'Data release',true,DataSetGroup.all.collect{|d| [d.data_release] if d.data_release && d.data_release != ''}.uniq.compact.sort %></strong></div>
    <div class="span1"><strong><%= sortable "data_set_groups.region_code", 'Region',true,DataSetGroup.all.collect{|d| [d.region_code] if d.region_code && d.region_code != ''}.uniq.compact.sort %></strong></div>
    <div class="span1"><strong><%= sortable "data_set_groups.data_type", 'Data type',true,DataSetGroup.all.collect{|d| [d.data_type] if d.data_type && d.data_type != ''}.uniq.compact.sort %></strong></div>
    <div class="span2"><strong><%= sortable "data_set_groups.filling", 'Filling',true,DataSetGroup.all.collect{|d| [d.filling] if d.filling && d.filling != ''}.uniq.compact.sort %></strong></div>
    <div class="span2"><strong><%= sortable "data_set_groups.suffix", 'Suffix',true %></strong></div>
  </div>
  <%= render(:partial => "data_set_group", :collection => @data_set_groups,:params => params) %>
</div>
<%= will_paginate(@data_set_groups) %>
<%= pageless(@data_set_groups.total_pages, url_for(:controller => :data_set_groups,:action => :index,:params => params), "#endless") %>

<script type="text/javascript">
  $("#removed").bootstrapSwitch();
  $('select').filter(".column_search").chosen({allow_single_deselect:true})
  $("#removed").on('switch-change', function() {
    $("form:first").submit()
  });
</script>

webmis/app/views/data_set_groups/new.html.erb
<%= render 'form' %>
<div class="row">
  <div class="span12">
    <%= link_to :back, :class => 'btn',:title => 'back to previous page' do %>
      <i class="icon icon-arrow-left"></i>
    <% end %>
    <%= link_to data_set_groups_path, :class => 'btn',:title => 'back to overview' do %>
      <i class="icon icon-arrow-up"></i>
    <% end %>
    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
  </div>
</div>

webmis/app/views/data_set_groups/show.html.erb
<%= render :partial => 'show_data' %>
<div class="row">
  <div class="span12">
    <%= link_to :back, :class => 'btn',:title => 'back to previous page' do %>
      <i class="icon icon-arrow-left"></i>
    <% end %>
    <%= link_to data_set_groups_path, :class => 'btn',:title => 'back to overview' do %>
      <i class="icon icon-arrow-up"></i>
    <% end %>
    <%= link_to handle_data_set_group_path(@data_set_group),:class => 'btn',:title => "handle" do %>
      <i class="icon-tasks" title="Handle"></i>
    <% end %>
    <%= link_to edit_data_set_group_path(@data_set_group),:class => 'btn',:title => "edit" do %>
      <i class="icon-edit" title="Edit"></i>
    <% end %>
    <%= next_prev_button("prev") %>
    <%= next_prev_button("next") %>
  </div>
</div>